// <auto-generated />
namespace PinetreeShop.CQRS.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Base : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Base));
        
        string IMigrationMetadata.Id
        {
            get { return "201610150633262_Base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
